kind: Template
apiVersion: v1
metadata:
  name: ${NAME}${SUFFIX}-deployment-template
  annotations:
    description: Deployment template for a NodeJS server connected to a MongoDB database.
    tags: nodejs
    iconClass: icon-nodejs
objects:
  - kind: NetworkPolicy
    apiVersion: networking.k8s.io/v1
    metadata:
      name: ${NAME}${SUFFIX}
      labels:
        name: ${NAME}${SUFFIX}
        app: ${APP_NAME}${SUFFIX}
        app-group: ${APP_GROUP}
        role: ${ROLE}
        env: ${TAG_NAME}
    spec:
      description: |
        Allow the agent and the frontend services to access the PI.
      ingress:
        - from:
            - podSelector:
                matchLabels:
                  role: ${AGENT_ROLE}
                  app: ${APP_NAME}${SUFFIX}
                  env: ${TAG_NAME}
              namespaceSelector:
                matchLabels:
                  name: ${NAMESPACE_NAME}
                  environment: ${TAG_NAME}
            - podSelector:
                matchLabels:
                  role: ${PUBLIC_FRONTEND_ROLE}
                  app: ${APP_NAME}${SUFFIX}
                  env: ${TAG_NAME}
              namespaceSelector:
                matchLabels:
                  name: ${NAMESPACE_NAME}
                  environment: ${TAG_NAME}
          ports:
            - protocol: TCP
              port: ${{SERVICE_PORT}}
      podSelector:
        matchLabels:
          role: ${ROLE}
          app: ${APP_NAME}${SUFFIX}
          env: ${TAG_NAME}

  - kind: Secret
    apiVersion: v1
    metadata:
      name: ${NAME}${SUFFIX}
      labels:
        name: ${NAME}${SUFFIX}
        app: ${APP_NAME}${SUFFIX}
        app.kubernetes.io/part-of: ${APP_NAME}${SUFFIX}
        app-group: ${APP_GROUP}
        role: ${ROLE}
        env: ${TAG_NAME}
    stringData:
      smtp-host: ${SMTP_SERVER_ADDRESS}
      smtp-port: ${SMTP_SERVER_PORT}
      admin-email: ${ADMIN_EMAIL}
      invite-subject: ${EMAIL_SUBJECT}
    type: Opaque

  - kind: Service
    apiVersion: v1
    metadata:
      name: ${NAME}${SUFFIX}
      annotations:
        description: Exposes and load balances the application pods
      labels:
        name: ${NAME}${SUFFIX}
        app: ${APP_NAME}${SUFFIX}
        app.kubernetes.io/part-of: ${APP_NAME}${SUFFIX}
        app-group: ${APP_GROUP}
        role: ${ROLE}
        env: ${TAG_NAME}
    spec:
      ports:
        - name: ${SERVICE_PORT}-tcp
          port: ${{SERVICE_PORT}}
          protocol: TCP
          targetPort: ${{SERVICE_PORT}}
      selector:
        name: ${NAME}${SUFFIX}

  - kind: DeploymentConfig
    apiVersion: v1
    metadata:
      name: ${NAME}${SUFFIX}
      annotations:
        description: Defines how to deploy the application server
        app.openshift.io/connects-to: >-
          [{"apiVersion":"apps.openshift.io/v1","kind":"DeploymentConfig","name":"${AGENT_SERVICE_NAME}${SUFFIX}"},
          {"apiVersion":"apps.openshift.io/v1","kind":"DeploymentConfig","name":"${DB_SERVICE}${DB_SUFFIX}"}]
      labels:
        name: ${NAME}${SUFFIX}
        app: ${APP_NAME}${SUFFIX}
        app.kubernetes.io/part-of: ${APP_NAME}${SUFFIX}
        app-group: ${APP_GROUP}
        role: ${ROLE}
        env: ${TAG_NAME}
    spec:
      strategy:
        type: Rolling
      triggers:
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - ${NAME}${SUFFIX}
            from:
              kind: ImageStreamTag
              namespace: ${IMAGE_NAMESPACE}
              name: ${SOURCE_IMAGE_NAME}:${TAG_NAME}
        - type: ConfigChange
      replicas: 1
      selector:
        name: ${NAME}${SUFFIX}
      template:
        metadata:
          name: ${NAME}${SUFFIX}
          labels:
            name: ${NAME}${SUFFIX}
            app: ${APP_NAME}${SUFFIX}
            app.kubernetes.io/part-of: ${APP_NAME}${SUFFIX}
            app-group: ${APP_GROUP}
            role: ${ROLE}
            env: ${TAG_NAME}
        spec:
          volumes:
            - name: ${NAME}${SUFFIX}-app-config-volume
              configMap:
                name: ${APP_CONFIG_MAP_NAME}${SUFFIX}
                items:
                  - key: ${APP_CONFIG_FILE_NAME}
                    path: ${APP_CONFIG_FILE_NAME}
            - name: ${NAME}${SUFFIX}-schema-config-volume
              configMap:
                name: ${APP_CONFIG_MAP_NAME}${SUFFIX}
                items:
                  - key: ${APP_SCHEMAS_FILE_NAME}
                    path: ${APP_SCHEMAS_FILE_NAME}
            - name: ${NAME}${SUFFIX}-invite-template-volume
              configMap:
                name: ${APP_CONFIG_MAP_NAME}${SUFFIX}
                items:
                  - key: ${APP_EMAIL_INVITE_FILE_NAME}
                    path: ${APP_EMAIL_INVITE_FILE_NAME}
          containers:
            - name: ${NAME}${SUFFIX}
              image: " "
              ports:
                - containerPort: ${{SERVICE_PORT}}
                  protocol: TCP
              readinessProbe:
                failureThreshold: 5
                periodSeconds: 30
                initialDelaySeconds: 3
                timeoutSeconds: 20
                httpGet:
                  path: /
                  port: ${{SERVICE_PORT}}
              livenessProbe:
                failureThreshold: 5
                periodSeconds: 60
                initialDelaySeconds: 30
                timeoutSeconds: 20
                httpGet:
                  path: /
                  port: ${{SERVICE_PORT}}
              env:
                - name: PORT
                  value: ${SERVICE_PORT}
                - name: DB_SERVICE
                  value: ${DB_SERVICE}${DB_SUFFIX}
                - name: DB_PORT
                  value: ${DB_PORT}
                - name: DB_NAME
                  value: ${DB_NAME}
                - name: DB_USER
                  valueFrom:
                    secretKeyRef:
                      name: ${DB_SERVICE}${DB_SUFFIX}
                      key: database-user
                - name: DB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: ${DB_SERVICE}${DB_SUFFIX}
                      key: database-password
                - name: AGENT_ADMIN_URL
                  value: http://${AGENT_SERVICE_NAME}${SUFFIX}:${AGENT_ADMIN_PORT}
                - name: AGENT_ADMIN_API_KEY
                  valueFrom:
                    secretKeyRef:
                      name: ${AGENT_SERVICE_NAME}${SUFFIX}
                      key: admin-api-key
                - name: SMTP_HOST
                  valueFrom:
                    secretKeyRef:
                      name: ${NAME}${SUFFIX}
                      key: smtp-host
                - name: SMTP_PORT
                  valueFrom:
                    secretKeyRef:
                      name: ${NAME}${SUFFIX}
                      key: smtp-port
                - name: ADMIN_EMAIL
                  valueFrom:
                    secretKeyRef:
                      name: ${NAME}${SUFFIX}
                      key: admin-email
                - name: EMAIL_SUBJECT
                  valueFrom:
                    secretKeyRef:
                      name: ${NAME}${SUFFIX}
                      key: invite-subject
                - name: PUBLIC_SITE_URL
                  value: ${PUBLIC_SITE_URL}
              resources:
                requests:
                  cpu: ${CPU_REQUEST}
                  memory: ${MEMORY_REQUEST}
                limits:
                  cpu: ${CPU_LIMIT}
                  memory: ${MEMORY_LIMIT}
              volumeMounts:
                - name: ${NAME}${SUFFIX}-app-config-volume
                  mountPath: ${APP_CONFIG_MOUNT_PATH}${APP_CONFIG_FILE_NAME}
                  subPath: ${APP_CONFIG_FILE_NAME}
                - name: ${NAME}${SUFFIX}-schema-config-volume
                  mountPath: ${APP_CONFIG_MOUNT_PATH}${APP_SCHEMAS_FILE_NAME}
                  subPath: ${APP_SCHEMAS_FILE_NAME}
                - name: ${NAME}${SUFFIX}-invite-template-volume
                  mountPath: ${APP_CONFIG_MOUNT_PATH}${APP_EMAIL_INVITE_FILE_NAME}
                  subPath: ${APP_EMAIL_INVITE_FILE_NAME}

parameters:
  - name: NAME
    displayName: Name
    description:
      The name assigned to all of the OpenShift resources associated to
      the server instance.
    required: true
    value: issuer-kit-api
  - name: APP_NAME
    displayName: App Name
    description: Used to group components together in the OpenShift console.
    required: true
    value: issuer
  - name: APP_GROUP
    displayName: App Group
    description: The name assigned to all of the deployments in this project.
    required: true
    value: issuer-kit-api
  - name: SUFFIX
    displayName: Suffix
    description: A suffix applied to all of the objects in this template.
    required: false
    value: ""
  - name: ROLE
    displayName: Role
    description:
      The role of this service within the application - used for Network
      Policies
    required: true
    value: api
  - name: AGENT_ROLE
    displayName: Agent Role
    description:
      The role of the agent service within the application - used for Network
      Policies
    required: true
    value: agent
  - name: PUBLIC_FRONTEND_ROLE
    displayName: Public Frontend Role
    description:
      The role of the public frontend service within the application - used for Network
      Policies
    required: true
    value: public-frontend
  - name: IMAGE_NAMESPACE
    displayName: Image Namespace
    required: true
    description:
      The namespace of the OpenShift project containing the imagestream
      for the application.
    value: devex-von-tools
  - name: NAMESPACE_NAME
    displayName: Namespace Name
    description: The name of the namespace being deployed to..
    required: true
    value: a99fd4
  - name: SERVICE_PORT
    displayName: Service Port
    required: true
    description: The port exposed by the controller.
    value: "8080"
  - name: DB_PORT
    displayName: Database Port
    required: true
    description: The port exposed by the database service.
    value: "27017"
  - name: DB_NAME
    displayName: Database Name
    required: true
    description:
      Name of the deployed database (see environment variables in deployed
      database).
    value: issuer_db
  - name: DB_APP_NAME
    displayName: App Name
    description: Used to group components together in the OpenShift console.
    required: true
    value: issuer-kit-shared
  - name: DB_SUFFIX
    displayName: Suffix
    description: A suffix applied to all of the objects in this template.
    required: false
    value: ""
  - name: DB_SERVICE
    displayName: Database Service Name
    description: The name of the database server/service.
    required: true
    value: issuer-kit-db
  - name: SOURCE_IMAGE_NAME
    displayName: Source Image Name
    description: The name of the image to use for this resource.
    required: true
    value: issuer-kit-api
  - name: TAG_NAME
    displayName: Environment TAG name
    description: The TAG name for this environment, e.g., dev, test, prod
    required: true
    value: latest
  - name: AGENT_SERVICE_NAME
    displayName: Agent Service name
    description: Agent service name
    required: true
    value: agent
  - name: AGENT_ADMIN_PORT
    displayName: Agent Admin Port
    description: Agent admin port
    required: true
    value: "8024"
  - name: SMTP_SERVER_ADDRESS
    displayName: SMTP Server Address
    description: SMTP Server Address
    required: true
    value: ""
  - name: SMTP_SERVER_PORT
    displayName: SMTP Server Port
    description: SMTP Server Port
    required: true
    value: ""
  - name: ADMIN_EMAIL
    displayName: Admin Email
    description: The email address to be used as sender for outgoing messages.
    required: true
    value: ""
  - name: EMAIL_SUBJECT
    displayName: Invite Email Subject
    description: The subject line for the email invites.
    required: false
    value: Invite from Issuer-Kit
  - name: PUBLIC_SITE_URL
    displayName: Public Site URL
    description: Public Site URL
    required: false
    value: https://issuer-kit.apps.silver.devops.gov.bc.ca/
  - name: APP_CONFIG_MAP_NAME
    displayName: Application Config Map Name
    description:
      The name of the configuration map holding the data to configure the
      application.
    required: true
    value: api-config
  - name: APP_CONFIG_MOUNT_PATH
    displayName: Application Config Mount Path
    description: The path to use to mount the configuration file(s).
    required: true
    value: /opt/app-root/src/config/
  - name: APP_CONFIG_FILE_NAME
    displayName: Application Config File Name
    description: The name of the application configuration file.
    required: true
    value: default.json
  - name: APP_SCHEMAS_FILE_NAME
    displayName: Application Schemas Config File Name
    description: The name of the application schemas configuration file.
    required: true
    value: schemas.json
  - name: APP_EMAIL_INVITE_FILE_NAME
    displayName: Application Email Invite File Name
    description: The name of the application email invite file.
    required: true
    value: invite-email.html
  - name: CPU_REQUEST
    displayName: Resources CPU Request
    description: The resources CPU request (in cores) for this build.
    required: true
    value: 10m
  - name: CPU_LIMIT
    displayName: Resources CPU Limit
    description: The resources CPU limit (in cores) for this build.
    required: true
    value: 300m
  - name: MEMORY_REQUEST
    displayName: Resources Memory Request
    description: The resources Memory request (in Mi, Gi, etc) for this build.
    required: true
    value: 10Mi
  - name: MEMORY_LIMIT
    displayName: Resources Memory Limit
    description: The resources Memory limit (in Mi, Gi, etc) for this build.
    required: true
    value: 256Mi
